version: '3.1'

services:
  db:
    # Use postgres development db.
    image: postgres:15-alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: starter
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 2s
      timeout: 2s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

  # Runs a PGAdminer web instance on port 8080. Be sure to select postgres as the
  # database then use the info above to login at the hostname `db`.
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data:
